### ISSUE TITLE
milkcocoa.csのファイル名が小文字になっている

### ISSUE THREAD

**Issue by ShirakawaYoshimaru** [m2wasabi/unity-milkcocoa-primitive#1]
Assets/Milkcocoa/Scripts/milkcocoa.csスクリプトファイル名が小文字になっており、
MilkcocaTestシーンのMilkccocoaゲームオブジェクトのMilkcocoaコンポーネントの参照が外れていたので報告致します！

**Comment by m2wasabi** [comment]
ご指摘ありがとうございます。
修正しました！
